function imogepicamweb(){var db='',ab=' top: -1000px;',Ab='" for "gwt:onLoadErrorFn"',yb='" for "gwt:onPropertyErrorFn"',jb='");',Bb='#',Nb='&',ic='.cache.js',Db='/',Jb='//',cc='35D274D1BBD0145116457A7966401913',ec='7B6094652FC5501293D46A0C61C57AE6',fc='9567ACE988AB6697DA5D6484266F9E1B',hc=':',sb='::',uc=':moduleBase',cb='<!doctype html>',eb='<html><head><\/head><body><\/body><\/html>',vb='=',Cb='?',gc='ABC2C661A98A1F4F96434C05C8B0E6FD',xb='Bad handler "',bb='CSS1Compat',hb='Chrome',gb='DOMContentLoaded',X='DUMMY',tc='Ignoring non-whitelisted Dev Mode URL: ',Qb='Unexpected exception in locale detection, using default: ',Pb='_',sc='__gwtDevModeHook:imogepicamweb',Ob='__gwt_Locale',Ib='base',Gb='baseUrl',S='begin',Y='body',R='bootstrap',Fb='clear.cache.gif',ub='content',Lb='default',dc='en',pc='end',ib='eval("',rc='file:',bc='fr',Yb='gecko',Zb='gecko1_8',T='gwt.codesvr.imogepicamweb=',U='gwt.codesvr=',oc='gwt/standard/standard.css',zb='gwt:onLoadErrorFn',wb='gwt:onPropertyErrorFn',tb='gwt:property',ob='head',mc='href',qc='http:',Vb='ie10',Xb='ie8',Wb='ie9',Z='iframe',Eb='img',V='imogepicamweb',ac='imogepicamweb.devmode.js',Hb='imogepicamweb.nocache.js',rb='imogepicamweb::',lb='javascript',$='javascript:""',jc='link',nc='loadExternalRefs',Kb='locale',Mb='locale=',pb='meta',nb='moduleRequested',mb='moduleStartup',Ub='msie',qb='name',_='position:absolute; width:0; height:0; border:none; left: -1000px;',kc='rel',Tb='safari',kb='script',_b='selectingPermutation',W='startup',lc='stylesheet',fb='undefined',$b='unknown',Rb='user.agent',Sb='webkit';var q=window;var r=document;t(R,S);function s(){var a=q.location.search;return a.indexOf(T)!=-1||a.indexOf(U)!=-1}
function t(a,b){if(q.__gwtStatsEvent){q.__gwtStatsEvent({moduleName:V,sessionId:q.__gwtStatsSessionId,subSystem:W,evtGroup:a,millis:(new Date).getTime(),type:b})}}
imogepicamweb.__sendStats=t;imogepicamweb.__moduleName=V;imogepicamweb.__errFn=null;imogepicamweb.__moduleBase=X;imogepicamweb.__softPermutationId=0;imogepicamweb.__computePropValue=null;imogepicamweb.__getPropMap=null;imogepicamweb.__gwtInstallCode=function(){};imogepicamweb.__gwtStartLoadingFragment=function(){return null};var u=function(){return false};var v=function(){return null};__propertyErrorFunction=null;var w=q.__gwt_activeModules=q.__gwt_activeModules||{};w[V]={moduleName:V};var A;function B(){D();return A}
function C(){D();return A.getElementsByTagName(Y)[0]}
function D(){if(A){return}var a=r.createElement(Z);a.src=$;a.id=V;a.style.cssText=_+ab;a.tabIndex=-1;r.body.appendChild(a);A=a.contentDocument;if(!A){A=a.contentWindow.document}A.open();var b=document.compatMode==bb?cb:db;A.write(b+eb);A.close()}
function F(k){function l(a){function b(){if(typeof r.readyState==fb){return typeof r.body!=fb&&r.body!=null}return /loaded|complete/.test(r.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(r.removeEventListener){r.removeEventListener(gb,d,false)}if(e){clearInterval(e)}}}
if(r.addEventListener){r.addEventListener(gb,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=C();var f=B();var g;if(navigator.userAgent.indexOf(hb)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(ib));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode(jb));g=f.createElement(kb);g.language=lb;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(kb);g.language=lb;g.text=c[i];e.appendChild(g);d(e,g)}}}
imogepicamweb.onScriptDownloaded=function(a){l(function(){m(a)})};t(mb,nb);var n=r.createElement(kb);n.src=k;r.getElementsByTagName(ob)[0].appendChild(n)}
imogepicamweb.__startLoadingFragment=function(a){return I(a)};imogepicamweb.__installRunAsyncCode=function(a){var b=C();var c=B().createElement(kb);c.language=lb;c.text=a;b.appendChild(c);b.removeChild(c)};function G(){var c={};var d;var e;var f=r.getElementsByTagName(pb);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(qb),k;if(j){j=j.replace(rb,db);if(j.indexOf(sb)>=0){continue}if(j==tb){k=i.getAttribute(ub);if(k){var l,m=k.indexOf(vb);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=db}c[j]=l}}else if(j==wb){k=i.getAttribute(ub);if(k){try{d=eval(k)}catch(a){alert(xb+k+yb)}}}else if(j==zb){k=i.getAttribute(ub);if(k){try{e=eval(k)}catch(a){alert(xb+k+Ab)}}}}}v=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;imogepicamweb.__errFn=e}
function H(){function e(a){var b=a.lastIndexOf(Bb);if(b==-1){b=a.length}var c=a.indexOf(Cb);if(c==-1){c=a.length}var d=a.lastIndexOf(Db,Math.min(c,b));return d>=0?a.substring(0,d+1):db}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=r.createElement(Eb);b.src=a+Fb;a=e(b.src)}return a}
function g(){var a=v(Gb);if(a!=null){return a}return db}
function h(){var a=r.getElementsByTagName(kb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(Hb)!=-1){return e(a[b].src)}}return db}
function i(){var a=r.getElementsByTagName(Ib);if(a.length>0){return a[a.length-1].href}return db}
function j(){var a=r.location;return a.href==a.protocol+Jb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==db){k=h()}if(k==db){k=i()}if(k==db&&j()){k=e(r.location.href)}k=f(k);return k}
function I(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return imogepicamweb.__moduleBase+a}
function J(){var i=[];var j;function k(a,b){var c=i;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var l=[];var m=[];function n(a){var b=m[a](),c=l[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
m[Kb]=function(){var b=null;var c=Lb;try{if(!b){var d=location.search;var e=d.indexOf(Mb);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(Nb,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){b=v(Kb)}if(!b){b=q[Ob]}if(b){c=b}while(b&&!u(Kb,b)){var h=b.lastIndexOf(Pb);if(h<0){b=null;break}b=b.substring(0,h)}}catch(a){alert(Qb+a)}q[Ob]=c;return b||Lb};l[Kb]={'default':0,en:1,fr:2};m[Rb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Sb)!=-1}())return Tb;if(function(){return b.indexOf(Ub)!=-1&&r.documentMode>=10}())return Vb;if(function(){return b.indexOf(Ub)!=-1&&r.documentMode>=9}())return Wb;if(function(){return b.indexOf(Ub)!=-1&&r.documentMode>=8}())return Xb;if(function(){return b.indexOf(Yb)!=-1}())return Zb;return $b};l[Rb]={gecko1_8:0,ie10:1,ie8:2,ie9:3,safari:4};u=function(a,b){return b in l[a]};imogepicamweb.__getPropMap=function(){var a={};for(var b in l){if(l.hasOwnProperty(b)){a[b]=n(b)}}return a};imogepicamweb.__computePropValue=n;q.__gwt_activeModules[V].bindings=imogepicamweb.__getPropMap;t(R,_b);if(s()){return I(ac)}var o;try{k([bc,Tb],cc);k([dc,Tb],ec);k([bc,Zb],fc);k([dc,Zb],gc);o=i[n(Kb)][n(Rb)];var p=o.indexOf(hc);if(p!=-1){j=parseInt(o.substring(p+1),10);o=o.substring(0,p)}}catch(a){}imogepicamweb.__softPermutationId=j;return I(o+ic)}
function K(){if(!q.__gwt_stylesLoaded){q.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=r.createElement(jc);b.setAttribute(kc,lc);b.setAttribute(mc,I(a));r.getElementsByTagName(ob)[0].appendChild(b);__gwt_stylesLoaded[a]=true}}
t(nc,S);c(oc);t(nc,pc)}
G();imogepicamweb.__moduleBase=H();w[V].moduleBase=imogepicamweb.__moduleBase;var L=J();if(q){var M=!!(q.location.protocol==qc||q.location.protocol==rc);q.__gwt_activeModules[V].canRedirect=M;if(M){var N=sc;var O=q.sessionStorage[N];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(O)){if(O&&(window.console&&console.log)){console.log(tc+O)}O=db}if(O&&!q[N]){q[N]=true;q[N+uc]=H();var P=r.createElement(kb);P.src=O;var Q=r.getElementsByTagName(ob)[0];Q.insertBefore(P,Q.firstElementChild||Q.children[0]);return false}}}K();t(R,pc);F(L);return true}
imogepicamweb.succeeded=imogepicamweb();